# Default values for express-hello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image: nikon5070/express-hello:latest

ingress:
  domain: nikon.host
  host: app

