apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.name }}-service
              servicePort: {{ .Values.ingress.port }}
