apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if .Values.basicAuth }}
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
      # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
      # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Please...'
    {{ end }}

spec:
  rules:
    - host: {{ .Values.ingress.host }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: {{ .Values.ingress.port }}
