apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  ports:
    - name: http
      port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.name }}-app
