name: DELETE

on:
  pull_request:
    types: [closed]
    branches:
      - 'master'
env:
  NAME_PROJECT: ${{ secrets.NAME_PROJECT }}

jobs:
  remove:
    runs-on: self-hosted
    steps:
      - name: helm delete
        run: |
          helm delete ${NAME_PROJECT}-${GITHUB_HEAD_REF}
