name: dev

on:
  pull_request:
    branches:
      - "master"
env:
  NAME_PROJECT: ${{ secrets.NAME_PROJECT }}
  CONTAINER_TEST: "nikon5070/express-hello"

  DOCKER_REGISTY_LOGIN: ${{ secrets.DOCKER_REGISTY_LOGIN }}
  DOCKER_REGISTY_PASS: ${{ secrets.DOCKER_REGISTY_PASS }}
  AUTH_BASIC: ${{ secrets.AUTH_BASIC }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: set auth
        run: |
          echo $AUTH_BASIC > ./devops/dev/nginx/.htpasswd
      - name: docker login
        run: |
          echo $DOCKER_REGISTY_PASS | docker login $DOCKER_REGISTY -u $DOCKER_REGISTY_LOGIN --password-stdin
      - name: build docker image
        run: |
          docker build -t $CONTAINER_TEST:${GITHUB_HEAD_REF}_${GITHUB_SHA} -f ./devops/Dockerfile .
          docker push $CONTAINER_TEST:${GITHUB_HEAD_REF}_${GITHUB_SHA}

  dev-deploy:
    needs: create-machine
    runs-on: self-hosted

    steps:
      - name: docker dev stack
        run: |
          APP_PORT="$(./devops/array.sh $GITHUB_HEAD_REF)"
          echo $APP_PORT
          docker stack deploy --compose-file ./devops/docker-compose-dev.yml ratio-dev-${GITHUB_HEAD_REF}

#  clear-unused-docker-containers:
#    needs: [dev-deploy]
#    runs-on: self-hosted
#
#    steps:
#      - name: clear
#        run: |
#          bash ./devops/clean.sh
