name: dev

on:
  pull_request:
    branches:
      - "master"
env:
  NAME_PROJECT: ${{ secrets.NAME_PROJECT }}
  CONTAINER_TEST: "nikon5070/express-hello"

  DOCKER_REGISTY_LOGIN: ${{ secrets.DOCKER_REGISTY_LOGIN }}
  DOCKER_REGISTY_PASS: ${{ secrets.DOCKER_REGISTY_PASS }}
  AUTH_BASIC: ${{ secrets.AUTH_BASIC }}

jobs:
  helm:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          helm install ${NAME_PROJECT}_${GITHUB_HEAD_REF} . \
            --set ingress.host=${GITHUB_HEAD_REF}
#  build:
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v2
#      - name: docker login
#        run: |
#          echo $DOCKER_REGISTY_PASS | docker login -u $DOCKER_REGISTY_LOGIN --password-stdin
#      - name: build docker image
#        run: |
#          docker build -t $CONTAINER_TEST:${GITHUB_HEAD_REF}_${GITHUB_SHA} -f ./devops/Dockerfile .
#      - name: push docker images in registy
#        run: |
#          docker push $CONTAINER_TEST:${GITHUB_HEAD_REF}_${GITHUB_SHA}
#      - name: pull docker images with registy
#        run: |
#          docker pull $CONTAINER_TEST:${GITHUB_HEAD_REF}_${GITHUB_SHA}

#  dev-deploy:
#    needs: build
#    runs-on: self-hosted
#
#    steps:
#      - name: docker dev stack
#        run: |
#          docker stack deploy \
#            -c ./devops/docker-compose-dev.yml ${NAME_PROJECT}_${GITHUB_HEAD_REF}

#  clear-unused-docker-containers:
#    needs: [dev-deploy]
#    runs-on: self-hosted
#
#    steps:
#      - name: clear
#        run: |
#          bash ./devops/clean.sh
