name: PRODUCTION

on:
  push:
    branches:
      - master
env:
  NAME_PROJECT: ${{ secrets.NAME_PROJECT }}

  DOCKER_REGISTY_LOGIN: ${{ secrets.DOCKER_REGISTY_LOGIN }}
  DOCKER_REGISTY_PASS: ${{ secrets.DOCKER_REGISTY_PASS }}

  CONTAINER_TEST: "nikon5070/express-hello"
  CONTAINER_PROD: "nikon5070/express-hello:latest"
  HELM_PATH: "./k8s/exp-helm"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          echo $DOCKER_REGISTY_PASS | docker login -u $DOCKER_REGISTY_LOGIN --password-stdin
      - name: build docker image
        run: |
          docker build -t ${CONTAINER_TEST}:${GITHUB_SHA} -f ./devops/Dockerfile .
      - name: push docker images in registy
        run: |
          docker push ${CONTAINER_TEST}:${GITHUB_SHA}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: helm install
        run: |
          helm upgrade $NAME_PROJECT $HELM_PATH \
            --install \
            --namespace "${NAME_PROJECT}-project" \
            --set ingress.host=$NAME_PROJECT \
            --set container.image="${CONTAINER_TEST}:${GITHUB_SHA}"
